---

- hosts: rke2_servers[0]
  roles:
    - role: k8s/secrets
      become: true

# - hosts: localhost
#   roles:
#     - role: k8s/charts
#       become: false

- hosts: rke2_servers[0]
  roles:
    - role: k8s/nodes
      become: true