---

# - hosts: rke2_servers[0]
#   vars_files:
#     - inventory/skaro/group_vars/vault.yaml
#   roles:
#     - role: k8s/secrets
#       become: true

# - hosts: localhost
#   vars_files:
#     - inventory/skaro/group_vars/vault.yaml
#   roles:
#     - role: k8s/charts
#       become: false

- hosts: rke2_servers[0]
  vars_files:
    - inventory/skaro/group_vars/vault.yaml
  roles:
    - role: k8s/nodes
      become: true