- name: Install a list of apt packages
  ansible.builtin.apt:
    pkg:
    - pip

- name: Install required python libraries
  pip:
    name:
      - kubernetes >= 12.0.0
      - PyYAML >= 3.11
      - jsonpatch

- name: Create namespaces
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.namespace }}"
  loop: "{{ secrets }}"
  no_log: true

- name: Create secrets
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
        labels: "{{ item.labels | default({}) }}"
      type: '{{ item.type | default("Opaque") }}'
      data: '{{ item.data | default({}) }}'
      stringData: '{{ item.stringData | default({}) }}'
  loop: "{{ secrets }}"
  no_log: true
