---
all:
  vars:
    install_rke2_version: v1.30.1+rke2r1

rke2_cluster:
  children:
    rke2_servers:
      hosts:
        davros.jsnouff.net:
          node_name: davros
          node_ip: 192.168.5.10
          advertise_address: 192.168.5.10
          node_taints:
            - node-role.kubernetes.io/control-plane=true:NoSchedule
    rke2_agents:
      hosts:
        oswin.jsnouff.net:
          node_name: oswin
          node_ip: 192.168.5.11
          advertise_address: 192.168.5.11
          node_roles:
            - worker
            - storage
        calcula.jsnouff.net:
          node_name: calcula
          node_ip: 192.168.5.12
          advertise_address: 192.168.5.12
          node_roles:
            - worker
            # - storage
            - gpu
        dalek-sec.jsnouff.net:
          node_name: dalek-sec
          node_ip: 192.168.5.15
          advertise_address: 192.168.5.16
          node_roles:
            - worker
            - storage
        dalek-caan.jsnouff.net:
          node_name: dalek-caan
          node_ip: 192.168.5.16
          advertise_address: 192.168.5.16
          node_roles:
            - worker
            - storage
        dalek-thay.jsnouff.net:
          node_name: dalek-thay
          node_ip: 192.168.5.9
          advertise_address: 192.168.5.9
          node_roles:
            - worker
            - gpu
          node_taints:
            - nvidia.com/gpu=true:NoSchedule
        # dalek-jast.jsnouff.net:
        #   node_name: dalek-jast
        #   node_ip: 192.168.5.8
        #   advertise_address: 192.168.5.8
        #   node_roles:
        #     - worker
        #     - gpu
        #   node_taints:
        #     - nvidia.com/gpu=true:NoSchedule